name: "Enrollment Confirmation"
description: "Confirm enrollment with code in the title"
title: "Enrollment confirmation CODE"
labels: ["Enrollment"]
body:
  - type: input
    id: dummy
    attributes:
      label: "Enrollment ID (for reference)"
      description: "Replace CODE in the title with this ID. You can leave this blank if already included above."
      placeholder: "e.g. ABC-ENR-2025-0123"
    validations:
      required: false
